### DISCUSSION TITLE
Confused About Setting Up Namespaces with OPL (ts Files)

### DISCUSSION THREAD

**Discussion by snasphysicist** [ory/keto#1125] [Q&A] [answered]
Hi All,

Short Summary: ORL ts file rules don't appear to get applied/followed in `v0.10.0-alpha.0` and I can't figure out why

We're looking at using ORY Keto so I'm trying it out now. I'm having some trouble setting up non-trivial namespaces & rules from ts files, I wonder if someone would be able to provide some guidance? I've been roughly trying to follow https://www.ory.sh/docs/keto/guides/userset-rewrites with a local deployment.

I'm running PostgreSQL & ORY Keto in docker containers as so.

```bash
docker run -p 5432:5432 --name="policy-db" --network="policy" --env POSTGRES_USER="admin" --env POSTGRES_PASSWORD="admin" --env POSTGRES_DB="policy" -d postgres:12

export DSN="postgresql://admin:admin@policy-db:5432/policy?sslmode=disable"

docker run --name="keto-migrate-up" --network="policy" --env DSN="$DSN" \
  -v /home/ssmith/Scratchpad/keto/local/cfg/:/app/configuration/ \
  -v /home/ssmith/Scratchpad/keto/local/ns/:/app/namespaces/ \
  oryd/keto --config /app/configuration/keto-configuration-local.yaml \
  migrate up --format json --yes

docker run --network="policy" --env DSN="$DSN" \
  -v /home/ssmith/Scratchpad/keto/local/cfg/:/app/configuration/ \
  -v /home/ssmith/Scratchpad/keto/local/ns/:/app/namespaces/ \
  oryd/keto --config /app/configuration/keto-configuration-local.yaml \
  namespace validate

docker run --name="keto-serve" --network="policy" --env DSN="$DSN" \
  -v /home/ssmith/Scratchpad/keto/local/cfg/:/app/configuration/ \
  -v /home/ssmith/Scratchpad/keto/local/ns/:/app/namespaces/ \
  -p 4466:4466 -p 4467:4467 \
  oryd/keto --config /app/configuration/keto-configuration-local.yaml \
  serve
```

The folder attached to `/app/configuration/` contains `keto-configuration-local.yaml`

```yaml
serve:

  write:
    host: 0.0.0.0
    cors:
      allowed_origins:
        - "*"
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - "Authorization"
        - "Content-Type"
      exposed_headers:
        - "Content-Type"
      allow_credentials: true
      max_age: 0
      debug: false
      enabled: true
    port: 4467

  metrics:
    host: 0.0.0.0
    cors:
      allowed_origins:
        - "*"
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - "Authorization"
        - "Content-Type"
      exposed_headers:
        - "Content-Type"
      allow_credentials: true
      max_age: 0
      debug: false
      enabled: true
    port: 8081

  read:
    host: 0.0.0.0
    cors:
      allowed_origins:
        - "*"
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - "Authorization"
        - "Content-Type"
      exposed_headers:
        - "Content-Type"
      allow_credentials: true
      max_age: 0
      debug: false
      enabled: true
    port: 4466

profiling: ""

log:
  format: json

  leak_sensitive_values: false
  redaction_text: ""

  level: trace


namespaces:
  - file:///app/configuration/

version: v0.10.0-alpha.0
```

My namespace ts file is (copied directly from the example):

```typescript
// Copyright © 2022 Ory Corp
// SPDX-License-Identifier: Apache-2.0
import { Namespace, SubjectSet, Context } from "@ory/keto-namespace-types"
class User implements Namespace {
  related: {
    manager: User[]
  }
}
class Group implements Namespace {
  related: {
    members: (User | Group)[]
  }
}
class Folder implements Namespace {
  related: {
    parents: (File | Folder)[]
    viewers: SubjectSet<Group, "members">[]
  }
  permits = {
    view: (ctx: Context): boolean =>
      this.related.viewers.includes(ctx.subject) ||
      this.related.parents.traverse((p) => p.permits.view(ctx)),
  }
}
class File implements Namespace {
  related: {
    parents: (File | Folder)[]
    viewers: (User | SubjectSet<Group, "members">)[]
    owners: (User | SubjectSet<Group, "members">)[]
  }
  // Some comment
  permits = {
    view: (ctx: Context): boolean =>
      this.related.parents.traverse((p) => p.permits.view(ctx)) ||
      this.related.viewers.includes(ctx.subject) ||
      this.related.owners.includes(ctx.subject),
    edit: (ctx: Context) => this.related.owners.includes(ctx.subject),
  }
}
```

The migrations, namespace file validation, and starting `serve` all seem to go fine.

The first thing I don't understand - when I include only the OPL/ts file with the namespaces and rules in the `namespaces` directory, when trying to create relation tuples everything will fail with a 404, and there will be log entries saying that the namespaces are not known.

So I added separate JSON files like `{"id": 0, "name": "Group"}`, etc... for File, Folder, User and then I was able to create relation tuples. I created the tuples from Python, following the example.

```python
from dataclasses import dataclass
from typing import Optional
import json
import requests

host = "localhost"
read_port = "4466"
write_port = "4467"


def write_url(path: str) -> str:
    return f"http://{host}:{write_port}/{path}"


def read_url(path: str) -> str:
    return f"http://{host}:{read_port}/{path}"


@dataclass
class SubjectSet:
    namespace: str
    object: str
    relation: Optional[str] = None


def create_relation_tuple(
    namespace: str,
    object: str,
    relation: str,
    subject_id: str = None,
    subject_set: SubjectSet = None
):
    payload = {
        "namespace": namespace,
        "object": object,
        "relation": relation,
    }
    if subject_id is not None:
        payload["subject_id"] = subject_id
    if subject_set is not None:
        payload["subject_set"] = {
            "namespace": subject_set.namespace,
            "object": subject_set.object,
        }
        if subject_set.relation is not None:
            payload["subject_set"]["relation"] = subject_set.relation
    url = write_url("admin/relation-tuples")
    r = requests.put(url, data=json.dumps(payload))
    r.raise_for_status()


def check_relation_tuple(
    namespace: str,
    object: str,
    relation: str,
    subject_set: SubjectSet,
) -> bool:
    payload = {
        "namespace": namespace,
        "object": object,
        "relation": relation,
        "subject_set": {
            "namespace": subject_set.namespace,
            "object": subject_set.object,
            "relation": subject_set.relation,
        },
    }
    url = read_url("relation-tuples/check")
    r = requests.post(url, data=json.dumps(payload))
    if r.status_code != 200 and r.status_code != 403:
        r.raise_for_status()
    return r.json()


create_relation_tuple("Group", "developer", "members", subject_id="Patrik")
create_relation_tuple("Group", "developer", "members", subject_set=SubjectSet(
    namespace="User",
    object="Patrik",
))
create_relation_tuple("Group", "developer", "members", subject_set=SubjectSet(
    namespace="User",
    object="Henning",
))
create_relation_tuple("Folder", "keto/", "viewers", subject_set=SubjectSet(
    namespace="Group",
    object="developer",
    relation="members"
))
create_relation_tuple("File", "keto/README.md", "parents", subject_set=SubjectSet(
    namespace="Folder",
    object="keto/",
))
create_relation_tuple("Folder", "keto/src/", "parents", subject_set=SubjectSet(
    namespace="Folder",
    object="keto/",
))
create_relation_tuple("File", "keto/src/main.go", "parents", subject_set=SubjectSet(
    namespace="Folder",
    object="keto/src/",
))
create_relation_tuple("File", "private", "owners", subject_set=SubjectSet(
    namespace="User",
    object="Henning",
))

print(check_relation_tuple("File", "keto/src/main.go", "view", SubjectSet(
    namespace="User",
    object="Patrik",
)))
print(check_relation_tuple("File", "private", "view", SubjectSet(
    namespace="User",
    object="Patrik",
)))
```

However, the first check `fails` with `allowed:  false`. As I understand, this is supposed to be granted via `Patrik` being a `User` who is a `member` of the `Group` `developers`, and the `members` of `Group` `developers` being `viewers` of `Folder` `keto/`, and `File` `keto/src/main.go`  having `parents` `keto/src/`, and `keto/src/` having `parents` `keto/` due to the rules in the ts configuration file. This suggests that the rules in the ts file are not actually being applied/followed/

- Is there any way to check within ORY Keto itself which rules have been configured (without adding & checking relation tuples)? 
- Is it possible to see those rules e.g. in the database tables?
- Is there any log message or other output which indicates which namespace configuration files have been successfully read and applied?

Thanks if you managed to read this far, and in advance for any help!
Scott

**Comment by snasphysicist** [comment, marked as answer]
I think I figured out part of this problem. I missed the subtle difference in how namespaces are configured "not from OPL" vs "from OPL", i.e.

not from OPL:

```yaml
namespaces: file:///app/namespaces/
```

from OPL:

```yaml
namespaces:
  location: file:///app/namespaces/
```

Maybe  it would be nice to make this more explicitly in the configuration, something like

```yaml
namespaces:
  not-opl: file:///foo/blah/  # whatever the correct term is for "not OPL"!
  opl: file:///app/namespaces/
```
