### DISCUSSION TITLE
Keto CLI TLS issues

### DISCUSSION THREAD

**Discussion by dmitry-exposure** [ory/keto#1740] [Q&A]
Hi, I am starting out with Keto and can't seem to get TLS to work. It's probably me doing something wrong so would appreciate any suggestions.

I am on MacOS and got keto `v0.14.0` via Homebrew tap as per documentation.

I have generated certificate and key with:

```bash
openssl req -x509 -newkey rsa:2048 -nodes \
  -keyout ory.key \
  -out ory.crt \
  -days 365 \
  -subj "/CN=localhost"
```

I then run it with: `keto serve -c keto.yml`. Here is my keto.yml:

```yaml
dsn: memory

namespaces:
  - id: 1
    name: member

serve:
  read:
    host: 127.0.0.1
    port: 4466
    tls:
      cert:
        path: ./ory.crt
      key:
        path: ./ory.key

  write:
    host: 127.0.0.1
    port: 4467
    tls:
      cert:
        path: ./ory.crt
      key:
        path: ./ory.key

```

It seems to be running fine. But no matter what i do I always get the TLS error:

```bash
# keto status --read-remote localhost:4466
Unable to get a check response: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
```

It does work without transport security:

```bash
# keto status --read-remote localhost:4466 --insecure-disable-transport-security
SERVING
```

There must be something obvious that I'm missing.
