### ISSUE TITLE
MySQL: Migration fails with syntax error - DROP CONSTRAINT

### ISSUE THREAD

**Issue by easyCZ** [ory/keto#1195]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When performing migrations on a MySQL (5.7) database, the migrations fail with a syntax error.

The migration itself is https://github.com/ory/keto/blob/master/internal/persistence/sql/migrations/sql/20220513200400000001_uuid-mapping-remove-check.mysql.up.sql

The problem is that in MySQL, there's no syntax for `DROP CONSTRAINT` which the migration defines - see https://stackoverflow.com/questions/14122031/how-to-remove-constraints-from-my-mysql-table

### Reproducing the bug

```
keto migrate up -c config.yaml
```

### Relevant log output

```shell
DEBU[2023-01-16T14:42:49+01:00] 1.6143 seconds                                audience=application service_name=Ory Keto service_version=v0.10.0-alpha.0

Could not apply migrations: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT keto_uuid_mappings_chk_1' at line 1
error executing migrations/sql/20220513200400000001_uuid-mapping-remove-check.mysql.up.sql, sql: ALTER TABLE keto_uuid_mappings DROP CONSTRAINT keto_uuid_mappings_chk_1;
```
```


### Relevant configuration

```yml
dsn: mysql://keto:pass@tcp(localhost:3306)/keto?sql_mode=''

log:
    level: debug

namespaces:
  - name: app
    id: 1

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467
```

### Version

v0.10.0-alpha.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes
