### ISSUE TITLE
Keto CLI cannot communicate with the containers

### ISSUE THREAD

**Issue by Gromitmugs** [ory/keto#1339]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hi, I was trying the Keto CLI for creating relationship tuple (the `create relation-tuples` command), but the command didn't seem to work. It just output "context deadline exceed". It looked like the CLI cannot connect with the serve. So, I did a further investigation by testing it with the `status` command. The output was "NOT_SERVING". However, with the same configuration, when I changed the image version from `oryd/keto:v0.11.1-alpha.0` to `oryd/keto:v0.7.0-alpha.1-sqlite`, it output "SERVING" and seemed to be working just fine. Therefore, I suppose the problem could be that of the new image version.

Edit: For more information, I did try sending a health check request on `http://0.0.0.0:4466/health/alive` to the `oryd/keto:v0.11.1-alpha.0` one, and it worked. The only thing that does not work right now is the CLI of v0.11.1-alpha.0 itself not being able to communitcate.

The docker compose configuration can be seen below.

### Reproducing the bug

```yaml
version: "3"

services:
  keto:
    image: oryd/keto:v0.11.1-alpha.0
    container_name: keto
    ports:
      - 4466:4466
      - 4467:4467
    command: serve -c /home/ory/keto.yml
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /home/ory

  keto-init:
    image: oryd/keto:v0.11.1-alpha.0
    environment:
      - KETO_WRITE_REMOTE=keto:4467
      - KETO_READ_REMOTE=keto:4466
    volumes:
      - type: bind
        source: .
        target: /home/ory
    command: status

```

### Relevant log output

```shell
docker-keto-init-1  | NOT_SERVING
docker-keto-init-1 exited with code 0
```

### Version

0.11.1-alpha.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by ChristianSch** [comment]
I still have the same problem, but I'm not sure it's the exact same cause.

I have the following setup.

1. docker-compose
2. 
```
version: "3.2"

services:
  keto:
    image: oryd/keto:v0.11.1-alpha.0
    ports:
      - "4466:4466"
      - "4467:4467"
    command: serve -c /home/ory/keto.yml
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /home/ory

  keto-init:
    image: oryd/keto:v0.11.1-alpha.0
    environment:
      - KETO_WRITE_REMOTE=keto:4467
      - KETO_READ_REMOTE=keto:4466
    volumes:
      - type: bind
        source: .
        target: /home/ory
    command: relation-tuple create /home/ory/relation-tuples
    restart: on-failure
```

3. keto installed via homebrew with the version 0.11.1-alpha.0 

The keto-init container spams the logs with the following:

```
2023-06-29 14:38:11 Error: context deadline exceeded
2023-06-29 14:38:11 Usage:
2023-06-29 14:38:11   keto relation-tuple create <relationships.json> [<relationships-dir>] [flags]
2023-06-29 14:38:11 
2023-06-29 14:38:11 Flags:
2023-06-29 14:38:11       --authority string                      Set the authority header for the remote gRPC server.
2023-06-29 14:38:11       --format string                         Set the output format. One of table, json, yaml, json-pretty, jsonpath and jsonpointer. (default "default")
2023-06-29 14:38:11   -h, --help                                  help for create
2023-06-29 14:38:11       --insecure-disable-transport-security   Disables transport security. Do not use this in production.
2023-06-29 14:38:11       --insecure-skip-hostname-verification   Disables hostname verification. Do not use this in production.
2023-06-29 14:38:11   -q, --quiet                                 Be quiet with output printing.
2023-06-29 14:38:11       --read-remote string                    Remote address of the read API endpoint. (default "127.0.0.1:4466")
2023-06-29 14:38:11       --write-remote string                   Remote address of the write API endpoint. (default "127.0.0.1:4467")
2023-06-29 14:38:11 
2023-06-29 14:38:11 Global Flags:
2023-06-29 14:38:11   -c, --config strings   Config files to load, overwriting in the order specified. (default [/home/ory/keto.yml])
2023-06-29 14:38:11 
```

and the local keto cli fails with the same error:

```
~/d/k/keto >>>  keto relation-tuple get --insecure-disable-transport-security                                                                                      (base) 6.8s  Thu Jun 29 14:37:50 2023
Error: context deadline exceeded
Usage:
  keto relation-tuple get [flags]

Flags:
      --authority string                      Set the authority header for the remote gRPC server.
      --format string                         Set the output format. One of table, json, yaml, json-pretty, jsonpath and jsonpointer. (default "default")
  -h, --help                                  help for get
      --insecure-disable-transport-security   Disables transport security. Do not use this in production.
      --insecure-skip-hostname-verification   Disables hostname verification. Do not use this in production.
      --namespace string                      Set the requested namespace
      --object string                         Set the requested object
      --page-size int32                       maximum number of items to return (default 100)
      --page-token string                     page token acquired from a previous response
  -q, --quiet                                 Be quiet with output printing.
      --read-remote string                    Remote address of the read API endpoint. (default "127.0.0.1:4466")
      --relation string                       Set the requested relation
      --subject-id string                     Set the requested subject ID
      --subject-set string                    Set the requested subject set; format: "namespace:object#relation"
      --write-remote string                   Remote address of the write API endpoint. (default "127.0.0.1:4467")

Global Flags:
  -c, --config strings   Config files to load, overwriting in the order specified. (default [/Users/christian/keto.yml])

context deadline exceeded
```

It's not a networking problem, as I can reach the keto container from my localhost just fine:

```
/ $ wget keto:4467/
Connecting to keto:4467 (172.23.0.2:4467)
wget: server returned error: HTTP/1.1 404 Not Found
```

For the `keto-init` it's a different story, still trying to find the problem:

```
/ $ wget keto:446/health/alive
Connecting to keto:4466 (172.23.0.2:4466)
wget: can't open 'alive': Permission denied
/ $ 
```
