### ISSUE TITLE
Limit applied before filtering

### ISSUE THREAD

**Issue by jackybourgeois** [ory/keto#280]
**Describe the bug**

Thanks for the great work!

On the endpoint listOryAccessControlPolicies, it looks like the limit of returned policies is applied before filtering by resource or subject. The default limit is 100. If the policies I want are beyond the 100th record, nothing is returned.

**Reproducing the bug**

1. Run keto
2. Insert more policies than the limit returned limit with PUT /engines/acp/ory/exact/policies
3. Fetch the list of Policies, filtering by a subject or resource that is part of the policies insert after the 100th with GET /engines/acp/ory/exact/policies
4. The return is null

If I increase the limit of returned policies, the policy I look for are returned.

_Server configuration_

```yaml
  ory-keto:
    image: oryd/keto:$KETO_VERSION
    container_name: ory-keto
    ports:
      - 4466:4466
    depends_on:
      - ory-hydra
      - ory-keto-migrate
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - DSN=postgres://$ORY_POSTGRES_USER:$ORY_POSTGRES_PASSWORD@ory-postgres:5432/$ORY_POSTGRES_DB?sslmode=disable
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_ID=$KETO_CLIENT_ID
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_SECRET=$KETO_CLIENT_SECRET
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_TOKEN_URL=$PROTOCOL://$HOST:$PORT/oauth2/token
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=$PROTOCOL://$HOST:$PORT/oauth2/introspect
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=$PROTOCOL://$HOST:$PORT/oauth2/token
    restart: on-failure
```

**Expected behavior**

I expect policies up to the limit, whether they have between inserted beyond the 100th policy or not.

**Environment**

- Version: v0.5.7
- Environment: Docker
