### ISSUE TITLE
Jaeger tracing does not work as intended with jaeger provider and b3 propagation

### ISSUE THREAD

**Issue by avamonitoring** [ory/keto#283]
**Describe the bug**

The propagation setting is not being picked up by Keto, so any propagated context using b3 will not work. Keto will always create root spans, and not child spans of the propagated span context.

**Reproducing the bug**

1. Configure Keto to use Jaeger tracing
2. Create a microservice that uses Jaeger tracing and propagates context using b3 propagation
3. From the microservice, invoke any Keto endpoint, making sure to propagate the current span context
4. Check trace in Jaeger
5. Keto will have created a root span rather than a child span

_Server logs_

N/A

_Server configuration_

  ```
 jaeger:
       local_agent_address: <jaeger-agent>l:6831
       propagation: b3
       sampling:
         server_url: http:/<jaeger-agent>:5778/sampling
         type: const
         value: 1
   service_name: ORY Keto

```
**Expected behavior**

Keto should honor the propagated b3 span context and create a child span rather than a root span.

**Environment**

N/A

**Additional context**

The problem is that the b3 configuration is not being picked up by the viper driver:

https://github.com/ory/keto/blob/master/driver/configuration/provider_viper.go#L61

Solution is to add a line of code that reads the propagation setting.

I will submit a PR for this.
