### ISSUE TITLE
Query relation tuples API returns 500 when no subject parameter present

### ISSUE THREAD

**Issue by Hekewa** [ory/keto#601]
**Describe the bug**

The [Query relation tuples](https://www.ory.sh/keto/docs/reference/api/#query-relation-tuples) API returns 500 with message `malformed string input` when called without the `subject` parameter. The docs state that only required parameter is `namespace`

**Reproducing the bug**

```
heikki@brantop:~$ curl -s -d '{ "namespace":"endpoints", "object":"/endpoint/MyGRPCEndpoint","relation": "access", "subject":"uuidv4-1"}' -X PUT localhost:4467/relation-tuples | jq
{
  "namespace": "endpoints",
  "object": "/endpoint/MyGRPCEndpoint",
  "relation": "access",
  "subject": "uuidv4-1"
}
heikki@brantop:~$ curl -s 'localhost:4466/relation-tuples?namespace=endpoints&subject=uuidv4-1' | jq
{
  "relation_tuples": [
    {
      "namespace": "endpoints",
      "object": "/endpoint/MyGRPCEndpoint",
      "relation": "access",
      "subject": "uuidv4-1"
    }
  ],
  "next_page_token": ""
}
heikki@brantop:~$ curl -s 'localhost:4466/relation-tuples?namespace=endpoints' | jq
{
  "error": {
    "code": 500,
    "status": "Internal Server Error",
    "message": "malformed string input"
  }
}
```

_Server logs_

```
time=2021-05-19T03:54:11Z level=info msg=started handling request http_request=map[headers:map[accept:*/* user-agent:curl/7.58.0] host:localhost:4466 method:GET path:/relation-tuples query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:127.0.0.1:35414 scheme:http]
time=2021-05-19T03:54:11Z level=error msg=An error occurred while handling a request audience=application error=map[message:malformed string input] http_request=map[headers:map[accept:*/* user-agent:curl/7.58.0] host:localhost:4466 method:GET path:/relation-tuples query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:127.0.0.1:35414 scheme:http] http_response=map[status_code:500] service_name=ORY Keto service_version=master
time=2021-05-19T03:54:11Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* user-agent:curl/7.58.0] host:localhost:4466 method:GET path:/relation-tuples query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:127.0.0.1:35414 scheme:http] http_response=map[status:500 text_status:Internal Server Error took:4.21138ms]
```

**Expected behavior**

Able to list all tuples in a namespace with `curl -s 'localhost:4466/relation-tuples?namespace=endpoints`

**Environment**

I'm testing against the `oryd/keto:v0.6.0-alpha.3` image on k8s with the helm chart (using `kubectl port-forward`)

**Comment by xlanor** [comment]
I've just tested this using alpha3 using the following `keto.yml` found in the folder `cat-videos-example` (modifed to add `endpoints` to namespaces`

```
version: v0.6.0-alpha.3

log:
  level: debug

namespaces:
  - id: 0
    name: videos
  - id: 1
    name: endpoints

dsn: memory

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467
```

Listing all tuples in namespace `videos` works fine.

```
❯ curl -s 'localhost:4466/relation-tuples?namespace=videos' | jq
{
  "relation_tuples": [
    {
      "namespace": "videos",
      "object": "/cats",
      "relation": "owner",
      "subject": "cat lady"
    },
    {
      "namespace": "videos",
      "object": "/cats",
      "relation": "view",
      "subject": "videos:/cats#owner"
    },
    {
      "namespace": "videos",
      "object": "/cats/1.mp4",
      "relation": "owner",
      "subject": "videos:/cats#owner"
    },
    {
      "namespace": "videos",
      "object": "/cats/1.mp4",
      "relation": "view",
      "subject": "*"
    },
    {
      "namespace": "videos",
      "object": "/cats/1.mp4",
      "relation": "view",
      "subject": "videos:/cats/1.mp4#owner"
    },
    {
      "namespace": "videos",
      "object": "/cats/2.mp4",
      "relation": "owner",
      "subject": "videos:/cats#owner"
    },
    {
      "namespace": "videos",
      "object": "/cats/2.mp4",
      "relation": "view",
      "subject": "videos:/cats/2.mp4#owner"
    }
  ],
  "next_page_token": ""
}
```

Creating tuples, then listing it, as per your sample, also works fine.

```
❯ curl -s -d '{ "namespace":"endpoints", "object":"/endpoint/MyGRPCEndpoint","relation": "access", "subject":"uuidv4-1"}' -X PUT localhost:4467/relation-tuples | jq
{
  "namespace": "endpoints",
  "object": "/endpoint/MyGRPCEndpoint",
  "relation": "access",
  "subject": "uuidv4-1"
}
❯  curl -s 'localhost:4466/relation-tuples?namespace=endpoints&subject=uuidv4-1' | jq
{
  "relation_tuples": [
    {
      "namespace": "endpoints",
      "object": "/endpoint/MyGRPCEndpoint",
      "relation": "access",
      "subject": "uuidv4-1"
    }
  ],
  "next_page_token": ""
}
❯ curl -s 'localhost:4466/relation-tuples?namespace=endpoints' | jq
{
  "relation_tuples": [
    {
      "namespace": "endpoints",
      "object": "/endpoint/MyGRPCEndpoint",
      "relation": "access",
      "subject": "uuidv4-1"
    }
  ],
  "next_page_token": ""
}
```

Can you post your `keto.yml`?

**Comment by Hekewa** [comment]
This is my values.yaml for the keto helm chart (chart: keto-0.7.0 app version: v0.6.0)
```
replicaCount: 1

image:
  repository: oryd/keto
  pullPolicy: IfNotPresent
  tag: "v0.6.0-alpha.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

keto:
  # https://www.ory.sh/keto/docs/reference/configuration
  config:
    namespaces:
      - id: 0
        name: endpoints
    serve:
      read:
        port: 4466
      write:
        port: 4467
  autoMigrate: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  privileged: false

ingress:
  read:
    enabled: false

service:
  read:
    type: ClusterIP
    port: 80
  write:
    type: ClusterIP
    port: 80

secret:
  enabled: false
  nameOverride: "keto-dsn"

autoscaling:
  enabled: false

nodeSelector: {}

extraEnv: []

tracing:
  datadog:
    enabled: false

tolerations: []

affinity: {}
```
And got the keto.yaml inside the pod mounted volume has this:
```
namespaces:
- id: 0
  name: endpoints
serve:
  read:
    port: 4466
  write:
    port: 4467
```
Also might be worth noting that the database is postgres.
