### ISSUE TITLE
Re-release v1.0.0-beta.x as v0.1.x-sandbox+oryos.x

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#63]
* [ ] `v0.1.1-sandbox+oryOS.1`
* [ ] `v0.1.2-sandbox+oryOS.2`
* [ ] `v0.1.3-sandbox+oryOS.3`
* [ ] `v0.1.4-sandbox+oryOS.4`
* [ ] `v0.1.5-sandbox+oryOS.5`
* [ ] `v0.1.6-sandbox+oryOS.6`
* [ ] `v0.1.7-sandbox+oryOS.7`
* [ ] `v0.1.8-sandbox+oryOS.8`
* [ ] `v0.1.9-sandbox+oryOS.9`

```yml
  release-npm:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/keto
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: |
          npm version -f --no-git-tag-version $CIRCLE_TAG
      - run: npm publish --access public
```

```
{
  "name": "@oryd/keto",
  "private": false,
  "version": "0.0.0-test.0",
  "description": "The official JavaScript / NodeJS SDK for ORY Keto.",
  "license": "Apache 2.0",
  "main": "sdk/js/swagger/src/index.js",
  "scripts": {
    "prettier": "prettier --single-quote --parser flow --no-semi --write \"sdk/js/**/*.js\""
  },
  "browser": {
    "fs": false
  },
  "dependencies": {
    "superagent": "~3.7.0",
    "opencollective": "^1.0.3"
  },
  "devDependencies": {
    "prettier": "^1.7.4"
  },
  "collective": {
    "type": "opencollective",
    "url": "https://opencollective.com/ory",
    "logo": "https://opencollective.com/ory/logo.txt"
  }
}
```

```

      - run: docker build --build-arg git_tag=$(git describe --tags) --build-arg git_commit=$(git rev-parse HEAD) -f Dockerfile -t oryd/keto:$(echo $CIRCLE_TAG | tr '+' '_') .
      - run: docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - run: docker push oryd/keto:$(echo $CIRCLE_TAG | tr '+' '_')
```
