### ISSUE TITLE
Missing namespace config results in not helpful error

### ISSUE THREAD

**Issue by zepatrik** [ory/keto#663]
**Describe the bug**

> I'm trying to run the service that I installed from brew on Mac OS I've got an error: unable to initialize config provider: bad file descriptor.

**Reproducing the bug**

Start Keto without namespace config. Defaults to `./keto_namespaces`, iirc, which then gives you the error.

_Server logs_

```
unable to initialize config provider: bad file descriptor
```

_Server configuration_

```yaml
dsn: memory

serve:
  read:
    host: localhost
    port: 9922
  write:
    host: localhost
    port: 9922
```

**Expected behavior**

At least a helpful error.

**Additional context**

Suspected culprit: https://github.com/ory/keto/blob/f8af777f0b2040aa00fe65a33ad0269595232124/internal/driver/config/namespace_watcher.go#L60

cc @rustamgaifullin
