### ISSUE TITLE
Cannot build keto v0.6.0. Unable to initialize service registry: stat : no such file or directory

### ISSUE THREAD

**Issue by kentngzz** [ory/keto#720]
**Describe the bug**

I could not start the latest v0.6.0 of Keto using Docker or docker-compose methods. The container crashes with error "unable to initialize service registry: stat : no such file or directory"

**Reproducing the bug**

On a fresh VMware,
1. git clone https://github.com/ory/keto
2. Edit docker-compose file with  
     volumes:
      - "./keto.yml:/home/ory/keto.yml:rw"
3. docker-compose up -d (had a postgres running beforehand)
4. The container failed to start with error "unable to initialize service registry: stat : no such file or directory"

**Expected behavior**

Docker container up and running

**Environment**
- Ubuntu 20.04.2 LTS (Focal Fossa)
- Version: Ory Keto v0.6.0-alpha.3

**Comment by zepatrik** [comment]
Can you add your `keto.yml`? I suspect this is related to #663

**Comment by kentngzz** [comment]
Here are my configs. I also used docker-compose-postgres.yml from Keto repo to setup the database

Docker-compose.yml:
```yml
version: '3'

services:
  keto:
    image: oryd/keto:v0.6.0-alpha.3
    ports:
      - "4466:4466"
      - "4467:4467"
    volumes:
      - "./keto.yml:/home/ory/keto.yml:rw"
    command: serve
    environment:
      - LOG_LEVEL=debug
      - PORT=4466
      - DSN=memory
    restart: on-failure
```
keto.yml
```yml
## ORY Keto Configuration
serve:
  write:
    host: localhost
    cors:
      allowed_origins:
        - https://example.com
        - https://*.example.com
        - https://*.foo.example.com
      allowed_methods:
        - GET
      allowed_headers:
        - ''
      exposed_headers:
        - ''
      allow_credentials: false
      max_age: -100000000
      debug: false
      enabled: false
    tls:
      cert:
        base64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlEWlRDQ0FrMmdBd0lCQWdJRVY1eE90REFOQmdr...
        path: path/to/file.pem
      key:
        base64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlEWlRDQ0FrMmdBd0lCQWdJRVY1eE90REFOQmdr...
        path: path/to/file.pem
    port: 4467
  read:
    host: localhost
    cors:
      allowed_origins:
        - https://example.com
        - https://*.example.com
        - https://*.foo.example.com
      allowed_methods:
        - GET
      allowed_headers:
        - ''
      exposed_headers:
        - ''
      allow_credentials: false
      max_age: -100000000
      debug: false
      enabled: false
    tls:
      cert:
        base64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlEWlRDQ0FrMmdBd0lCQWdJRVY1eE90REFOQmdr...
        path: path/to/file.pem
      key:
        base64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlEWlRDQ0FrMmdBd0lCQWdJRVY1eE90REFOQmdr...
        path: path/to/file.pem
    port: 4466
profiling: cpu
log:
  format: text
  leak_sensitive_values: false
  level: panic
tracing:
  service_name: ORY Hydra
  providers:
    jaeger:
      propagation: jaeger
      sampling:
        type: const
        value: 1
        server_url: http://localhost:5778/sampling
      local_agent_address: 127.0.0.1:6831
  provider: jaeger
namespaces: http://a.aaa
version: v0.6.0-alpha.3
dsn: postgres://dbuser:secret@127.0.0.1:5432/accesscontroldb
```
