### ISSUE TITLE
CORS config values are ignored

### ISSUE THREAD

**Issue by johanforssell** [ory/keto#788]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).

### Describe the bug

When making CORS preflight requests against Keto the response does not contain any headers. We do get a 200 OK repsonse.

Further more it seems like the CORS config values are totally ignored.

### Reproducing the bug

Call your local Keto with curl:
```
$ curl -X OPTIONS http://127.0.0.1:4466/check -i
HTTP/1.1 200 OK
Allow: GET, OPTIONS, POST
Date: Mon, 22 Nov 2021 11:42:17 GMT
Content-Length: 0
```

It does not matter what I write in the config `serve.read.cors.allowed_methods`. 
When specifying POST, GET, PUT, PATCH, DELETE as allowed methods the response is still just `Allow: GET, OPTIONS, POST`.
The `cors.debug` flag seems to do nothing, etc, etc.

### Relevant log output

```shell
$ curl -X OPTIONS http://127.0.0.1:4466/check -i                                                                                                               

HTTP/1.1 200 OK
Allow: GET, OPTIONS, POST
Date: Mon, 22 Nov 2021 11:56:35 GMT
Content-Length: 0
```

### Relevant configuration

```yml
read:
    host: localhost
    port: 4466  
    cors: 
      debug: true
      enabled: true
      allowed_origins:
        - "https://localhost"
        - "https://*.localhost"
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
```

### Version

v0.7.0-alpha.1

### In which environment are you deploying?

Other

### Additional Context

tested on macos and linux
