### ISSUE TITLE
Keto is returning 200 OK on expand HTTP API on non existing resource

### ISSUE THREAD

**Issue by nickjn92** [ory/keto#855]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Keto is returning `200` with the response body being `null` as a string when using the expand HTTP API on non-existing relation tuple.
Expected behavior should be to return a 404 and this is one of the responses in the [HTTP API reference](https://www.ory.sh/docs/keto/reference/rest-api#operation/getExpand).

### Reproducing the bug

1. Start keto, e.g. with the attached `docker-compose.yml` in relevant configuration section
2. Run a simple expand query using curl `curl http://localhost:4466/expand?namespace=organization&object=test&relation=access -v`
3. Observe response
```
*   Trying 127.0.0.1:4466...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4466 (#0)
> GET /expand?namespace=organization&object=test&relation=access HTTP/1.1
> Host: localhost:4466
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Tue, 15 Mar 2022 14:24:00 GMT
< Content-Length: 5
< 
null
* Connection #0 to host localhost left intact

```

### Relevant log output

```shell
keto_1  | time=2022-03-15T14:24:00Z level=info msg=started handling request http_request=map[headers:map[accept:*/* user-agent:curl/7.68.0] host:localhost:4466 method:GET path:/expand query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:172.31.0.1:40226 scheme:http]
keto_1  | time=2022-03-15T14:24:00Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* user-agent:curl/7.68.0] host:localhost:4466 method:GET path:/expand query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:172.31.0.1:40226 scheme:http] http_response=map[headers:map[content-type:application/json; charset=utf-8] size:5 status:200 text_status:OK took:761.115µs]
```

### Relevant configuration

```yml
serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

namespaces:
  - id: 0
    name: organization
```

### Version

0.8.0-alpha.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

`docker-compose.yml`
```yaml
version: "3"

services:
  keto:
    image: oryd/keto:v0.8.0-alpha.2
    ports:
      - "4466:4466"
      - "4467:4467"
    command: serve
    environment:
      - LOG_LEVEL=debug
      - PORT=4466
      - DSN=memory
    volumes:
      - type: bind
        source: ./keto.yml
        target: /home/ory/keto.yml

```

`keto.yml`
```yaml
version: v0.8.0-alpha.2

log:
  level: debug

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

namespaces:
  - id: 0
    name: organization

dsn: memory

```
